[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/webhook-test/*"
  to = "/.netlify/functions/webhook-test"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
